#!/bin/sh

# generate testsuite autoconf
CONFIG="t/include.ac"
echo > $CONFIG
echo '# this part is autogenerated by autogen.sh' >> $CONFIG
echo >> $CONFIG
find t/ -not -path 't/mock/bin/*' -name '*.in' | sed 's/\.in$//g' | while read line; do
	echo "AC_CONFIG_FILES($line)" >> $CONFIG
done
for binary in btrfs rsync ; do
    echo "AC_CONFIG_FILES(t/mock/bin/${binary}:t/mock/bin/mock-exec.in, chmod +x t/mock/bin/${binary})" >> $CONFIG
done
echo >> $CONFIG
echo '# this part had been autogenerated by autogen.sh' >> $CONFIG

autoreconf -i
