name: Report a bug
description: Report a bug in rsnapshot
labels: [bug]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Carefully read and work through this check list
      options:
        - label: I'm reporting a bug
          required: true
        - label: I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.
          required: true
  - type: textarea
    id: what-i-did
    attributes:
      label: What did you do?
      description: What steps should we follow to reproduce the problem?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe exactly what happened
    validations:
      required: true
  - type: textarea
    id: what-i-expected
    attributes:
      label: What did you expect to happen
      description: What do you think _should have_ happened?
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: My configuration
      description: "Copy n paste your config here. This shell snippet may be useful for stripping blank lines and comments: `sed 's/ *#.*//' /path/to/rsnapshot.conf | grep .`"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **server OS**: FreeBSD 12
          - **snapshot_root filesystem**: ZFS
      value: |
          OS:
          Filesystem:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: Any other useful information?
      placeholder: For example a snippet from your logs

