blank_issues_enabled: false
contact_links:
  - name: Get support on the mailing list
    url: https://sourceforge.net/p/rsnapshot/mailman/rsnapshot-discuss/
    about: Join the mailing list for community support
