#!/bin/sh

set -e

case "$1" in
    configure)
		files="/etc/cron.monthly/rsnapshot /etc/cron.daily/rsnapshot \
			/etc/cron.hourly/rsnapshot /etc/cron.weekly/rsnapshot \
			/etc/default/rsnapshot"
		for file_to_remove in $files
		do
			dpkg-maintscript-helper rm_conffile \
				$file_to_remove 1.3.1-6 rsnapshot -- "$@"
		done
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
