name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"] # , "windows-latest"]
        perl: ["5.40", "5.38", "5.20", "5.14", "5.12"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: install automake on macos
        if: contains(matrix.os, 'macos')
        run: brew install automake
      - name: ssh for tests
        run: |
          ssh-keygen -t "rsa" -f ~/.ssh/id_rsa -N ""
          cp ~/.ssh/{id_rsa.pub,authorized_keys}
      - name: build
        run: |
          ./autogen.sh
          ./configure
          make
      - name: test
        run: make test